on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: install_go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - name: install_dependencies
      run: |
        go get github.com/joho/godotenv
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}
    - name: Install sandbox
      run: doctl sandbox install
    - name: Install sandbox
      run: doctl sandbox connect
    - name: Deploy function
      run: doctl sandbox deploy ./src --verbose-build
