on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: install_go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - name: install_dependencies
      run: |
        go install github.com/joho/godotenv
    - name: GitHub Action for DigitalOcean - doctl
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.DO_TOKEN }}
    - name: Deploy function
      run: doctl sandbox deploy ./src --verbose-build
